### ISSUE TITLE
Add default help text to Slack `/hours` command

### ISSUE THREAD

**Issue by bitmanic** [collectiveidea/hourglass#19]
Right now, we can use the `/hours [some time period]` command from within Slack to get a summary of our Harvest hours. However, nothing is returned if the time period is left out of the command (e.g. `/hours`). It'd be nice if a default time range was assumed, or if helper text that prompted for a time period was returned. For instance, typing `/hours` would result in Slackbot sending a message saying "Which period would you like to see hours for?"

**Comment by laserlemon** [comment]
:+1:

**Comment by bitmanic** [comment]
This is great. Thanks, @laserlemon!
